// 本地 Chromium 检查；使用独立用户目录，不连接用户正在使用的浏览器。
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import http from 'node:http';
import {spawn} from 'node:child_process';
import {fileURLToPath} from 'node:url';
const root=path.resolve(fileURLToPath(new URL('..',import.meta.url)));
const out=path.resolve(root,'../tmp/reading-qa');fs.mkdirSync(out,{recursive:true});
const userData=path.join(root,'.sites-runtime',`reading-qa-${Date.now()}`);fs.mkdirSync(userData,{recursive:true});
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml'};
const server=http.createServer((req,res)=>{
  const p=path.resolve(root,'dist','.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname==='/'?'/index.html':new URL(req.url,'http://localhost').pathname));
  if(!p.startsWith(path.join(root,'dist')+path.sep)){res.writeHead(403);return res.end();}
  try{res.writeHead(200,{'Content-Type':mime[path.extname(p)]||'application/octet-stream'});res.end(fs.readFileSync(p));}catch{res.writeHead(404);res.end();}
});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const port=server.address().port,chrome='C:/Program Files/Google/Chrome/Application/chrome.exe';
const proc=spawn(chrome,['--headless=new','--no-first-run','--no-default-browser-check','--remote-debugging-port=0',`--user-data-dir=${userData}`,'about:blank'],{windowsHide:true,stdio:['ignore','ignore','pipe']});
const errors=[];let socket;
const delay=ms=>new Promise(r=>setTimeout(r,ms));
try{
  let debugPort;
  for(let i=0;i<100;i++){try{debugPort=Number(fs.readFileSync(path.join(userData,'DevToolsActivePort'),'utf8').split('\n')[0]);if(debugPort)break;}catch{}await delay(100);}
  assert.ok(debugPort,'Chrome debug port');
  const targets=await (await fetch(`http://127.0.0.1:${debugPort}/json/list`)).json();
  socket=new WebSocket(targets.find(t=>t.type==='page').webSocketDebuggerUrl);
  await new Promise((resolve,reject)=>{socket.onopen=resolve;socket.onerror=reject;});
  let serial=0;const pending=new Map();
  socket.onmessage=ev=>{const v=JSON.parse(ev.data);if(v.id){const p=pending.get(v.id);pending.delete(v.id);v.error?p.reject(Error(v.error.message)):p.resolve(v.result);}else if(v.method==='Runtime.exceptionThrown')errors.push(v.params.exceptionDetails.text);};
  const send=(method,params={})=>new Promise((resolve,reject)=>{const id=++serial;pending.set(id,{resolve,reject});socket.send(JSON.stringify({id,method,params}));});
  await send('Runtime.enable');await send('Page.enable');
  const evaluate=async expression=>{const r=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value;};
  const open=async(id,width=1400,height=1000)=>{
    await send('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:1,mobile:width<600});
    await send('Page.navigate',{url:`http://127.0.0.1:${port}/#/lesson/${id}`});
    for(let i=0;i<50;i++){if(await evaluate(`document.readyState==='complete' && !!document.querySelector('.worked-answer') && location.hash.includes('${id}')`))break;await delay(100);}
    await evaluate("document.documentElement.style.scrollBehavior='auto'");
  };
  await open('c-pointer');
  assert.equal(await evaluate("document.querySelector('.worked-answer').open"),false);
  assert.equal(await evaluate("!!document.querySelector('.quiz-card:not(.written-card) .quiz-answer')"),false);
  await evaluate("document.querySelector('.worked-answer summary').click()");
  assert.equal(await evaluate("document.querySelector('.worked-answer').open"),true);
  await evaluate("document.querySelector('.worked-answer summary').click()");
  await evaluate("document.querySelector('[data-action=walk-next]').click()");
  assert.equal(await evaluate("document.querySelector('.walkthrough').dataset.step"),'1');
  await evaluate("document.querySelector('[data-action=walk-reset]').click(); document.querySelector('#diagram').scrollIntoView()");
  const capture=async name=>{const r=await send('Page.captureScreenshot',{format:'png'});fs.writeFileSync(path.join(out,name+'.png'),Buffer.from(r.data,'base64'));};
  await capture('pointer-desktop');
  await open('ds-list');
  await evaluate("for(let i=0;i<30;i++)document.querySelector('[data-action=walk-next]').click(); document.querySelector('#diagram').scrollIntoView()");
  assert.ok(await evaluate("document.querySelector('.walk-status').textContent.includes('返回新链头')"));
  await capture('list-desktop');
  await open('p-spi');
  for(let mode=0;mode<4;mode++){
    await evaluate(`{const s=document.querySelector('#spi-mode');s.value=${mode};s.dispatchEvent(new Event('change',{bubbles:true}));for(let i=0;i<8;i++)document.querySelector('[data-action=walk-next]').click();}`);
    assert.ok(await evaluate("document.querySelector('.walk-watch').textContent.includes('1 0 1 1')"));
    if(mode===3){await evaluate("document.querySelector('#diagram').scrollIntoView()");await capture('spi-mode3');}
  }
  await open('c-array-pointer',390,844);
  assert.equal(await evaluate('innerWidth'),390,'mobile viewport matches screen');
  await evaluate("document.querySelector('#diagram').scrollIntoView()");
  assert.ok(await evaluate("document.documentElement.scrollWidth <= innerWidth+1"),'no mobile page overflow');
  await capture('array-mobile');
  await open('c-sizeof',1400,1000);
  assert.ok(await evaluate("document.querySelector('.basic-reading').textContent.includes('不是普通函数')"));
  assert.equal(await evaluate("document.querySelector('.advanced-reasoning').open"),false);
  assert.equal(await evaluate("document.querySelector('.basic-optional').open"),false);
  await evaluate("document.querySelector('#basics').scrollIntoView()");
  await capture('sizeof-beginner-desktop');
  await evaluate("document.querySelector('.basic-optional summary').click()");
  assert.equal(await evaluate("document.querySelector('.basic-optional').open"),true);
  await open('c-dereference',390,844);
  assert.ok(await evaluate("document.documentElement.scrollWidth <= innerWidth+1"),'no beginner mobile page overflow');
  await evaluate("document.querySelector('#basics').scrollIntoView()");
  await capture('dereference-beginner-mobile');
  await open('c-pointer-declare',390,844);
  assert.ok(await evaluate("document.documentElement.scrollWidth <= innerWidth+1"),'no symbol list mobile overflow');
  await evaluate("document.querySelector('.symbol-list').scrollIntoView()");
  await capture('pointer-symbols-mobile');
  await open('c-pointer',390,844);
  await evaluate("document.querySelector('[data-action=lesson-view][data-value=practice]').click();document.querySelector('[data-action=lesson-group][data-value=advanced]').click()");
  assert.equal(await evaluate("document.querySelector('.lesson-reading-view').hidden"),true);
  assert.equal(await evaluate("document.querySelector('#written').hidden"),false);
  assert.equal(await evaluate("document.querySelector('.written-answer').open"),false);
  await evaluate("document.querySelector('.written-answer summary').click();document.querySelector('.written-card').scrollIntoView()");
  assert.equal(await evaluate("document.querySelector('.written-answer').open"),true);
  assert.ok(await evaluate("document.documentElement.scrollWidth <= innerWidth+1"),'written mobile fits');
  await capture('written-exam-mobile');
  await evaluate("document.querySelector('.written-editor').value='我的推导：a=3,b=6,c=9';document.querySelector('.written-editor').dispatchEvent(new Event('input',{bubbles:true}))");
  await send('Page.reload');await delay(300);
  await evaluate("document.querySelector('[data-action=lesson-view][data-value=practice]').click();document.querySelector('[data-action=lesson-group][data-value=advanced]').click()");
  assert.equal(await evaluate("document.querySelector('.written-editor').value"),'我的推导：a=3,b=6,c=9');
  assert.equal(await evaluate("document.querySelector('.written-answer').open"),false);
  await evaluate("document.querySelector('#quiz-exam-ptr-post [data-action=choose][data-choice=\"0\"]').click();document.querySelector('#quiz-exam-ptr-post [data-action=submit-answer]').click()");
  assert.ok(await evaluate("document.querySelector('#quiz-exam-ptr-post').textContent.includes('回答正确')"));
  const correctLetter=await evaluate("document.querySelector('#quiz-exam-ptr-post .option.correct .letter').textContent");
  assert.ok(await evaluate("document.querySelector('#quiz-exam-ptr-post .quiz-answer').textContent.includes('正确答案："+correctLetter+"')"));
  await send('Emulation.setDeviceMetricsOverride',{width:1400,height:1000,deviceScaleFactor:1,mobile:false});
  await evaluate("location.hash='#/practice/c'");await delay(100);
  assert.equal(await evaluate("document.querySelector('#practice-module').value"),'c');
  assert.equal(await evaluate("document.querySelector('#practice-difficulty').value"),'进阶');
  assert.ok(await evaluate("!!document.querySelector('.written-card') && !!document.querySelector('.challenge-card')"));
  await capture('mixed-exam-desktop');
  await evaluate("const s=document.querySelector('#practice-type');s.value='written';s.dispatchEvent(new Event('change',{bubbles:true}))");
  assert.equal(await evaluate("!!document.querySelector('[data-action=choose]')"),false);
  await evaluate("location.hash='#/challenge/coding-bounded-atoi'");await delay(100);
  assert.equal(await evaluate("document.querySelector('#challenge-solution').hidden"),true);
  await evaluate("document.querySelector('[data-action=solution]').click()");
  assert.equal(await evaluate("document.querySelector('#challenge-solution').hidden"),false);
  assert.ok(await evaluate("document.querySelector('#challenge-solution').textContent.includes('INT32_MIN')"));
  await open('c-pointer',1440,1000);
  await evaluate("document.querySelector('[data-action=lesson-view][data-value=practice]').click();document.querySelector('[data-action=lesson-group][data-value=coding]').click()");
  assert.equal(await evaluate("document.querySelector('#coding').hidden"),false);
  assert.equal(await evaluate("document.querySelector('.lesson-practice-view').hidden"),false);
  assert.equal(await evaluate("document.querySelector('#challenge-solution').hidden"),true);
  assert.ok(await evaluate("document.querySelector('.editor-pane').getBoundingClientRect().left > document.querySelector('.problem-pane').getBoundingClientRect().right"),'desktop panes side by side');
  await evaluate("{const s=document.querySelector('#lesson-coding-select');s.value='lab-buffer-move';s.dispatchEvent(new Event('change',{bubbles:true}));}");
  assert.ok(await evaluate("document.querySelector('.workbench-editor').value.includes('move_region')"));
  await evaluate("{const e=document.querySelector('.workbench-editor');e.value='// QA draft: preserve buffer bounds';e.dispatchEvent(new Event('input',{bubbles:true}));}");
  assert.equal(await evaluate("document.querySelector('[data-draft-status]').textContent"),'已保存到本机');
  await evaluate("{const s=document.querySelector('#lesson-coding-select');s.value='lab-swap';s.dispatchEvent(new Event('change',{bubbles:true}));}");
  assert.ok(await evaluate("document.querySelector('.workbench-editor').value.includes('swap_int')"));
  await evaluate("{const s=document.querySelector('#lesson-coding-select');s.value='lab-buffer-move';s.dispatchEvent(new Event('change',{bubbles:true}));}");
  assert.equal(await evaluate("document.querySelector('.workbench-editor').value"),'// QA draft: preserve buffer bounds');
  await evaluate("document.querySelector('[data-action=lesson-group][data-value=basic]').click()");
  assert.equal(await evaluate("document.querySelector('#quiz').hidden"),false);
  assert.equal(await evaluate("document.querySelectorAll('#quiz .quiz-card').length"),3,'all original basics retained');
  await evaluate("document.querySelector('[data-action=lesson-group][data-value=coding]').click();window.scrollTo(0,0)");
  await capture('coding-lesson-desktop');
  await evaluate("location.hash='#/challenge/lab-buffer-move'");await delay(100);
  assert.equal(await evaluate("document.querySelector('.workbench-editor').value"),'// QA draft: preserve buffer bounds');
  assert.equal(await evaluate("document.querySelector('#challenge-solution').hidden"),true);
  await evaluate("document.querySelector('[data-action=solution]').click()");
  assert.equal(await evaluate("document.querySelector('[data-action=solution]').getAttribute('aria-expanded')"),'true');
  const downloadDir=path.join(out,'downloads-'+Date.now());fs.mkdirSync(downloadDir,{recursive:true});
  await send('Browser.setDownloadBehavior',{behavior:'allow',downloadPath:downloadDir});
  await evaluate("document.querySelector('[data-action=download-code]').click()");await delay(300);
  assert.equal(fs.readFileSync(path.join(downloadDir,'lab-buffer-move.c'),'utf8'),'// QA draft: preserve buffer bounds');
  await open('cpp-copy',1440,1000);
  await evaluate("document.querySelector('[data-action=lesson-view][data-value=practice]').click()");
  assert.ok(await evaluate("document.querySelector('.workbench-editor').value.includes('TinyText')"));
  await capture('cpp-coding-desktop');
  await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
  await delay(300);
  assert.ok(await evaluate("document.querySelector('.sidebar').getBoundingClientRect().right<=1"),'mobile sidebar fully closed after transition');
  assert.ok(await evaluate("document.documentElement.scrollWidth <= innerWidth+1"),'coding mobile no overflow');
  assert.ok(await evaluate("document.querySelector('.editor-pane').getBoundingClientRect().top >= document.querySelector('.problem-pane').getBoundingClientRect().bottom"),'mobile panes stack');
  await evaluate("document.querySelector('.editor-pane').scrollIntoView()");
  await capture('coding-editor-mobile');
  await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});
  await delay(300);
  await evaluate("location.hash='#/home'");await delay(100);
  await capture('workspace-home');
  await open('linux-fork');
  assert.ok(await evaluate("document.querySelector('.topic-foundation').textContent.includes('写时复制')"));
  await evaluate("document.querySelector('[data-action=walk-next]').click();document.querySelector('#diagram').scrollIntoView()");
  assert.equal(await evaluate("document.querySelectorAll('.topic-flow-card').length"),2);
  assert.ok(await evaluate("document.querySelector('.walk-watch').textContent.includes('101')"));
  await capture('linux-fork-desktop');
  await open('linux-devicetree',390,844);await delay(300);
  assert.ok(await evaluate("document.documentElement.scrollWidth<=innerWidth+1"),'device-tree tables contained on mobile');
  assert.ok(await evaluate("document.querySelector('.lesson-refs').textContent.includes('Devicetree')"));
  await evaluate("document.querySelector('.topic-table-scroll').scrollIntoView()");
  await capture('devicetree-mobile');
  await open('r-nvic-priority');
  await evaluate("for(let i=0;i<3;i++)document.querySelector('[data-action=walk-next]').click()");
  assert.ok(await evaluate("document.querySelector('.walk-watch').textContent.includes('0x50')"));
  await open('ds-valley');
  await evaluate("for(let i=0;i<4;i++)document.querySelector('[data-action=walk-next]').click();document.querySelector('#diagram').scrollIntoView()");
  assert.ok(await evaluate("document.querySelector('.walk-watch').textContent.includes('平台版总数')"));
  await capture('valley-desktop');
  await open('ds-valley-longest');
  await evaluate("for(let i=0;i<6;i++)document.querySelector('[data-action=walk-next]').click()");
  assert.ok(await evaluate("document.querySelector('.walk-status').textContent.includes('3→5')"));
  await evaluate("document.querySelector('[data-action=walk-reset]').click()");
  assert.equal(await evaluate("document.querySelector('.walkthrough').dataset.step"),'0');
  await evaluate("location.hash='#/lesson/ds-valley-longest/coding'");await delay(100);
  assert.equal(await evaluate("document.querySelector('#challenge-solution').hidden"),true);
  assert.ok(await evaluate("document.querySelector('.workbench-editor').value.includes('longest_valley')"));
  await evaluate("document.querySelector('[data-action=solution]').click()");
  assert.ok(await evaluate("document.querySelector('#challenge-solution').textContent.includes('down')"));
  await send('Page.navigate',{url:'http://127.0.0.1:'+port+'/#/companies'});
  for(let i=0;i<50;i++){if(await evaluate("!!document.querySelector('.apply-company')"))break;await delay(100);}
  await evaluate("localStorage.removeItem('embedded-applications-v1')");
  await send('Page.reload');await delay(300);
  assert.equal(await evaluate("document.querySelectorAll('.apply-company').length"),15);
  const ids=await evaluate("[...document.querySelectorAll('.apply-company')].map(b=>b.dataset.id)");
  const firstId=ids[0];
  assert.equal(await evaluate("document.querySelector('.apply-official').target"),'_blank');
  await evaluate("document.querySelector('[data-rec-note]').value='<script>window.bad=1</script>';document.querySelector('[data-rec-note]').dispatchEvent(new Event('input',{bubbles:true}))");
  await evaluate("document.querySelector('[data-rec-status]').value='已投递';document.querySelector('[data-rec-status]').dispatchEvent(new Event('change',{bubbles:true}))");
  await send('Page.reload');await delay(300);
  assert.deepEqual(await evaluate("[...document.querySelectorAll('.apply-company')].map(b=>b.dataset.id)"),ids);
  assert.equal(await evaluate("document.querySelector('[data-rec-note]').value"),'<script>window.bad=1</script>');
  assert.equal(await evaluate("document.querySelector('[data-rec-status]').value"),'已投递');
  assert.equal(await evaluate("window.bad||0"),0,'notes do not execute');
  await evaluate("document.querySelector('[data-rec=undo-applied]').click()");
  assert.equal(await evaluate("document.querySelector('[data-rec-status]').value"),'待投递');
  await evaluate("document.querySelector('[data-rec-status]').value='暂不合适';document.querySelector('[data-rec-status]').dispatchEvent(new Event('change',{bubbles:true}));document.querySelector('[data-rec=fill]').click()");
  assert.ok(!(await evaluate("[...document.querySelectorAll('.apply-company')].map(b=>b.dataset.id)")).includes(firstId));
  await evaluate("document.querySelector('[data-rec-status]').value='暂不合适';document.querySelector('[data-rec-status]').dispatchEvent(new Event('change',{bubbles:true}));document.querySelector('[data-rec=fill]').click()");
  await evaluate("document.querySelector('[data-rec=mode][data-value=all]').click();document.querySelector('[name=query]').value='汇川技术';document.querySelector('#application-search').dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}))");
  assert.equal(await evaluate("document.querySelectorAll('.apply-company').length"),1,'company search');
  await evaluate("document.querySelector('[data-rec=add-today]').click()");
  assert.ok(await evaluate("document.querySelector('.apply-message').textContent.includes('勾选')"));
  await evaluate("document.querySelector('[data-rec-confirm]').checked=true;document.querySelector('[data-rec-confirm]').dispatchEvent(new Event('change',{bubbles:true}));document.querySelector('[data-rec=add-today]').click()");
  assert.ok(await evaluate("document.querySelector('.apply-message').textContent.includes('已加入')"));
  assert.ok(await evaluate("JSON.parse(localStorage.getItem('embedded-applications-v1')).days[Object.keys(JSON.parse(localStorage.getItem('embedded-applications-v1')).days).at(-1)].length===15"));
  // Restore a genuine backup through the file-input flow, including daily plan.
  const chosen=await evaluate("document.querySelector('[data-rec-note]').dataset.recNote");
  await evaluate("window.confirm=()=>true;{const dt=new DataTransfer();const day=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());const id="+JSON.stringify(chosen)+";dt.items.add(new File([JSON.stringify({type:'embedded-applications',version:1,records:{[id]:{status:'待投递',confirmed:true,note:'恢复后的备注'}},days:{[day]:[id]}})],'backup.json',{type:'application/json'}));const input=document.querySelector('#application-import');input.files=dt.files;input.dispatchEvent(new Event('change',{bubbles:true}));}");
  await delay(150);
  assert.equal(await evaluate("document.querySelector('[data-rec-note]').value"),'恢复后的备注');
  assert.ok(await evaluate("document.querySelector('.apply-message').textContent.includes('已恢复')"));
  await evaluate("document.querySelector('[name=query]').value='';document.querySelector('#application-search').dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));document.querySelector('[data-rec=mode][data-value=today]').click();document.querySelector('#recruitment-root').scrollIntoView()");
  await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});await delay(80);
  assert.ok(await evaluate("document.querySelector('.apply-detail').getBoundingClientRect().left>document.querySelector('.apply-list').getBoundingClientRect().right"),'desktop panels beside each other');
  await capture('applications-desktop');
  await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await delay(200);
  assert.ok(await evaluate("document.documentElement.scrollWidth<=innerWidth+1"),'application mobile fits');
  await capture('applications-mobile');

  // 所有图解帧都无浏览器执行异常，且按钮可用；下面遍历所有课程检查真实 DOM。
  const {lessons}=await import('../dist/content.js');
  for(const l of lessons){
    await evaluate(`location.hash='#/lesson/${l.id}'`);await delay(10);
    assert.equal(await evaluate("document.querySelector('.worked-answer').open"),false,l.id);
  }
  assert.deepEqual(errors,[]);
  console.log(`PASS browser: ${lessons.length} lessons, hidden/revealed worked answers, step/reset, 4 SPI modes, mobile overflow. Screenshots: ${out}`);
}finally{if(socket)socket.close();proc.kill();server.close();}
